* Week 05
[2016-08-22 Mon 15:52]
In Week 5, you will be learning how to train Neural Networks. The Neural Network is one of the most powerful learning algorithms (when a linear classifier doesn't work, this is what I usually turn to), and this week's videos explain the 'backprogagation' algorithm for training these models. In this week's programming assignment, you'll also get to implement this algorithm and see it work for yourself.

The Neural Network programming exercise will be one of the more challenging ones of this class. So please start early and do leave extra time to get it done, and I hope you'll stick with it until you get it to work! As always, if you get stuck on the quiz and programming assignment, you should post on the Discussions to ask for help. (And if you finish early, I hope you'll go there to help your fellow classmates as well.)
** Cost Function and Backpropagation
[2016-08-22 Mon 15:52]
*** Cost Function
[2016-08-22 Mon 15:53]
*** Backpropagation Algorithm
[2016-08-22 Mon 15:53]
*** Backpropagation Intuition
[2016-08-22 Mon 15:53]
** Backpropagation in Practice
[2016-08-22 Mon 15:52]
*** Implementation Note: Unrolling Parameters
[2016-08-22 Mon 15:53]
*** Gradient Checking
[2016-08-22 Mon 15:54]
*** Random Initialization
[2016-08-22 Mon 15:54]
*** Putting it Together
[2016-08-22 Mon 15:54]
** Application of Neural Networks
[2016-08-22 Mon 15:53]
*** Autonomous Driving
[2016-08-22 Mon 15:54]
