* Week 06
[2016-08-30 Tue 12:02]
In Week 6, you will be learning about systematically improving your learning algorithm. The videos for this week will teach you how to tell when a learning algorithm is doing poorly, and describe the 'best practices' for how to 'debug' your learning algorithm and go about improving its performance.

We will also be covering machine learning system design. To optimize a machine learning algorithm, you’ll need to first understand where the biggest improvements can be made. In these lessons, we discuss how to understand the performance of a machine learning system with multiple parts, and also how to deal with skewed data.

When you're applying machine learning to real problems, a solid grasp of this week's content will easily save you a large amount of work.
** Evaluating a Learning Algorithm
[2016-08-30 Tue 12:02]
*** Deciding What to Try Next
[2016-08-30 Tue 12:03]
*** Evaluating a Hypothesis
[2016-08-30 Tue 12:03]
*** Model Selection and Train/Validation/Test Sets
[2016-08-30 Tue 12:03]
** Bias vs. Variance
[2016-08-30 Tue 12:03]
*** Diagnosing Bias vs. Variance
[2016-08-30 Tue 12:03]
*** Regularization and Bias/Variance
[2016-08-30 Tue 12:04]
*** Learning Curves
[2016-08-30 Tue 12:04]
*** Deciding What to Do Next Revisited
[2016-08-30 Tue 12:04]
** Quiz
[2016-08-30 Tue 12:03]
** Programming Assignment
[2016-08-30 Tue 12:03]
